In [1]:
import numpy as np

In [5]:
from __future__ import division #py2 to resolve follow case

In [2]:
5/2

2

In [3]:
5.0/2

2.5

In [6]:
5/2 #here we see without mentioning float 5.0

2.5

In [8]:
array1 = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
array1*array1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [11]:
array1 - array1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
1 / array1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [13]:
array1 ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]])