In [1]:
import pandas as pd
import numpy as np
from  pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])


In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

C:\Users\swapn\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [13]:
dframe1

X         Y         Z
0  0.125071  1.370631 -0.111497
1  0.085918 -1.923477 -0.723587
2  0.918426 -1.345235 -0.345860
3  0.163353  0.325843 -0.563134

In [14]:
dframe2

Y         Q         X
0 -1.535326 -0.106627  0.838570
1 -0.727512  0.711513 -0.630587
2 -1.198861 -0.953924 -0.500832

In [15]:
pd.concat([dframe1,dframe2])

C:\Users\swapn\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  0.125071  1.370631 -0.111497
1       NaN  0.085918 -1.923477 -0.723587
2       NaN  0.918426 -1.345235 -0.345860
3       NaN  0.163353  0.325843 -0.563134
0 -0.106627  0.838570 -1.535326       NaN
1  0.711513 -0.630587 -0.727512       NaN
2 -0.953924 -0.500832 -1.198861       NaN

In [17]:
pd.concat([dframe1,dframe2],ignore_index=True)

C:\Users\swapn\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  0.125071  1.370631 -0.111497
1       NaN  0.085918 -1.923477 -0.723587
2       NaN  0.918426 -1.345235 -0.345860
3       NaN  0.163353  0.325843 -0.563134
4 -0.106627  0.838570 -1.535326       NaN
5  0.711513 -0.630587 -0.727512       NaN
6 -0.953924 -0.500832 -1.198861       NaN

In [18]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'