In [1]:
import numpy as np

In [2]:
arr =  np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)

A

array([ 0.25821454,  0.12131798, -0.03583324, -0.41837407, -2.66382197,
        1.06100459, -1.01479907,  0.46100567, -0.52872992, -0.15469587])

In [9]:
B = np.random.randn(10)
B

array([-0.01806448,  0.14615622, -0.06715932, -0.84425321,  0.77861326,
        0.30750084,  1.9173648 ,  1.15505326, -0.7890216 ,  2.222302  ])

In [10]:
# Binary Function
np.add(A,B)

array([ 0.24015006,  0.2674742 , -0.10299256, -1.26262728, -1.88520871,
        1.36850543,  0.90256572,  1.61605892, -1.31775152,  2.06760613])

In [11]:
np.maximum(A,B)

array([ 0.25821454,  0.14615622, -0.03583324, -0.41837407,  0.77861326,
        1.06100459,  1.9173648 ,  1.15505326, -0.52872992,  2.222302  ])

In [12]:
np.minimum(A,B)

array([-0.01806448,  0.12131798, -0.06715932, -0.84425321, -2.66382197,
        0.30750084, -1.01479907,  0.46100567, -0.7890216 , -0.15469587])

In [13]:
website = 'https://www.energysage.com'
import webbrowser
webbrowser.open(website)

True